services:
  aidevops: # Next.js application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      # Specifies the default environment file for the application container.
      - .env.local
    restart: always